steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - ${_DOCKERFILE}
      - --build-arg
      - VITE_API_BASE=${_VITE_API_BASE}
      - --tag
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}

substitutions:
  _IMAGE: ''
  _DOCKERFILE: ''
  _VITE_API_BASE: ''
