"""Convert Spleen BDF fonts to C bitmap tables: 95 glyphs (0x20..0x7E), row-major, MSB first."""
import sys, re
FONTS = [('6x12', 6, 12), ('8x16', 8, 16), ('12x24', 12, 24), ('16x32', 16, 32), ('32x64', 32, 64)]
def parse(path):
    txt = open(path).read()
    m = re.search(r'^FONTBOUNDINGBOX (-?\d+) (-?\d+) (-?\d+) (-?\d+)$', txt, re.M)
    W, H, XOFF, YOFF = map(int, m.groups())
    glyphs = {}
    for block in re.findall(r'STARTCHAR.*?ENDCHAR', txt, re.S):
        enc = int(re.search(r'^ENCODING (-?\d+)$', block, re.M).group(1))
        if not (0x20 <= enc <= 0x7e): continue
        bw, bh, bx, by = map(int, re.search(r'^BBX (-?\d+) (-?\d+) (-?\d+) (-?\d+)$', block, re.M).groups())
        rows = block.split('BITMAP\n', 1)[1].split('\nENDCHAR')[0].split('\n')
        rows = [r.strip() for r in rows if r.strip()]
        assert len(rows) == bh, (enc, len(rows), bh)
        cell = [[0]*W for _ in range(H)]
        baseline = H + YOFF          # row index of the baseline, from the top
        top = baseline - by - bh
        left = bx - XOFF
        for r, hexrow in enumerate(rows):
            bits = int(hexrow, 16)
            nbits = len(hexrow) * 4
            for c in range(bw):
                if bits & (1 << (nbits - 1 - c)):
                    y, x = top + r, left + c
                    if 0 <= y < H and 0 <= x < W: cell[y][x] = 1
        glyphs[enc] = cell
    assert len(glyphs) == 95, (path, len(glyphs))
    return W, H, glyphs
def rows_to_bytes(cell, W):
    bpr = (W + 7) // 8
    out = []
    for row in cell:
        v = 0
        for x in range(W):
            if row[x]: v |= 1 << (W - 1 - x) if W % 8 == 0 else 1 << (bpr*8 - 1 - x)
        out += [(v >> (8*(bpr-1-i))) & 0xff for i in range(bpr)]
    return out
lic = open('/tmp/spleen/LICENSE').read().strip().splitlines()
h = ['/* Bitmap fonts for HTN OS: Spleen by Frederic Cambus (BSD 2-Clause), converted from the BDF',
     ' * sources at https://github.com/fcambus/spleen by scripts/bdf2c.py. Do not edit by hand.',
     ' *']
h += [(' * ' + l).rstrip() for l in lic] + [' */', '#pragma once', '', '#include <stdint.h>', '',
      'typedef struct {', '    uint8_t width;', '    uint8_t height;', '    uint8_t bytes_per_row;',
      '    /* 95 glyphs for 0x20..0x7E, height*bytes_per_row bytes each, rows top to bottom;',
      '       pixel x of a row is bit (7 - x%8) of byte x/8, so byte 0 bit 7 is the leftmost pixel. */',
      '    const uint8_t *glyphs;', '} font_info_t;', '']
h += ['typedef enum {'] + [f'    FONT_{n.upper()},' for n,_,_ in FONTS] + ['    FONT_COUNT', '} font_t;', '',
      'extern const font_info_t FONTS[FONT_COUNT];', '']
c = ['/* Generated by scripts/bdf2c.py from Spleen (BSD 2-Clause, see fonts.h). Do not edit. */',
     '#include "fonts.h"', '']
for name, W, H in FONTS:
    w, hgt, glyphs = parse(f'/tmp/spleen/spleen-{name}.bdf')
    assert (w, hgt) == (W, H), (name, w, hgt)
    data = []
    for enc in range(0x20, 0x7f): data += rows_to_bytes(glyphs[enc], W)
    c.append(f'static const uint8_t font_{name}_data[{len(data)}] = {{')
    for i in range(0, len(data), 16):
        c.append('    ' + ', '.join(f'0x{b:02x}' for b in data[i:i+16]) + ',')
    c.append('};'); c.append('')
    if name == '8x16':  # sanity render 'A' and 'g' to stderr
        for ch in 'Ag':
            for row in glyphs[ord(ch)]: print(''.join('#' if p else '.' for p in row), file=sys.stderr)
            print(file=sys.stderr)
c.append('const font_info_t FONTS[FONT_COUNT] = {')
for name, W, H in FONTS:
    c.append(f'    [FONT_{name.upper()}] = {{ {W}, {H}, {(W+7)//8}, font_{name}_data }},')
c.append('};')
open('firmware/main/fonts.h', 'w').write('\n'.join(h).rstrip('\n') + '\n')
open('firmware/main/fonts.c', 'w').write('\n'.join(c) + '\n')
print('written', sum(1 for l in c if l.startswith('    0x')), 'data lines')
