skip_local_validator = true

[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
badge_escrow = "6kdZgrhS4FANagxKHiMoJzm2wEp2NRgNYTkjpYYRjtdD"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
