skip_local_validator = true

[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
htn_quest = "9UkH8LeXw8jpQFZVNS3yk9LmkzsFAh54MK7SGP8jTsfY"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
